const FORMAT_DATE = ["DD/MM/YYYY", "DD-MM-YYYY", "YYYY-MM-DD", "YYYY/MM/DD"];
const FORMAT_TIME = ["HH:mm:ss", "HH:mm"];
const FORMAT_DATE_TIME = [...FORMAT_DATE, ...FORMAT_TIME];

export { FORMAT_DATE, FORMAT_TIME, FORMAT_DATE_TIME };
